### ISSUE TITLE
Error while building the program 

### ISSUE THREAD

**Issue by lorenz-py** [progweb/gpx2video#1]
```
 In file included from /home/lore/gpx2video/src/oiioutils.cpp:1:
 /home/lore/gpx2video/src/oiioutils.h:12:10: fatal error: OpenImageIO/imageio.h: No such file or directory
    12 | #include <OpenImageIO/imageio.h>
       |          ^~~~~~~~~~~~~~~~~~~~~~~
 compilation terminated.
 make[2]: *** [CMakeFiles/gpx2video.dir/build.make:132: CMakeFiles/gpx2video.dir/src/oiioutils.cpp.o] Error 1
 make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/gpx2video.dir/all] Error 2
 make: *** [Makefile:136: all] Error 2

```

Hi, I was trying to build the last version of your project and this error occurred. I'm on Manjaro.

**Comment by progweb** [comment]
Don't forget to install all dependancies:
- libevent>=2.0.0
- libcurl>=7.38.0
- libavutil>=3.0.0
- libavformat>=3.0.0
- libavcodec>=3.0.0
- libavfilter>=3.0.0
- libswresample>=2.0.0
- libswscale>=3.0.0
- geographiclib
- cairo

With Debian: 
apt-get install libevent-dev libcurl4-gnutls-dev libavutil-dev libavformat-devlibavcodec-dev libavfilter-dev libswresample-dev libswscale-dev libgeographic-dev libcairo2-dev

**Comment by lorenz-py** [comment]
Thank you so much. It worked.
