### ISSUE TITLE
[BUILD] Unable to find cairo.h and libevent pkgconfig

### ISSUE THREAD

**Issue by benfulton** [progweb/gpx2video#15]
Attempting to build on Ubuntu 22.04 I saw these two errors. To successfully build I ran the following two commands:

```
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/
export CPLUS_INCLUDE_PATH=/usr/include/cairo/

```

And the build succeeded.

**Comment by progweb** [comment]
You shouldn't run these commands. 

I don't have the time to commit Dockerfile and add job/pipeline in github. But you can try:

`
docker pull ubuntu:22.04
docker run --rm -t -i -v `pwd`/../:/data --workdir=/data/ --name=gpx2video ubuntu:22.04 /bin/bash
cd gpx2video
mkdir build.ubuntu
cd build.ubuntu
apt-get update
apt-get dist-upgrade
apt-get install build-essential cmake pkg-config libevent-dev libssl-dev libcurl4-gnutls-dev libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev libswresample-dev libswscale-dev libopenexr-dev libopenimageio-dev libgeographic-dev libcairo2-dev
cmake ..
make
`

gpx2video builds without issue.

**Comment by progweb** [comment]
Can’t be produced
