### ISSUE TITLE
[BUG] gpx file almost empty when extractinf with -f 3 option

### ISSUE THREAD

**Issue by bgse51** [progweb/gpx2video#17]
Hi,

I have been able to compile, then I ran this command :
./gpx2video -v -m ${fichier_gopro} -o ${dossier_exports}/gpx/output.gpx -f 3 extract

fichier_gopro is the .LRV file from a gopro 6 black camera

However, the gpx created file is almost empty :

`<?xml version="1.0" encoding="utf-8"?>
<gpx version="1.0"
  creator="gpx2video"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.topografix.com/GPX/1/0"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd">
  <trk>
    <number>1</number>
    <trkseg>
    </trkseg>
  </trk>
</gpx>`

The same command with -f 2 extract option is working fine : the .bin file is created and is the exact same file than the one created on windows by this tool : https://github.com/jeeve/GoproToGpx/blob/master/GPMD2CSV.bat)

I can send you the .bin file if needed

another try with a gopro 7 black camera file is working better :
the gpx file has a content, but only around 1 trkpt by second, (sometime3 trkpt in a second, sometimes only 1 point for 3 seconds)
though I know the camera records arond 18 gps position by second.

merci

**Comment by progweb** [comment]
Hi,

Indeed, I'm interested in the LRV file with GoPro6. Here, I have GoPro 6 too, I don't have issue to extract GPS data.

"-f 2" extract all data grabbed from sensor (gps, accelerometer, etc...) Are you sure that your binary contains GPS data ?
"-f 3" extract only GPS data to write a GPX file.
"-f 1" dump all data in txt format. You should understand why you don't have GPS data. (maybe no signal / no fix)

**Comment by bgse51** [comment]
hello
the LRV file I used does not contain any GPS data.
so, this is not an issue.
