### ISSUE TITLE
[BUG] Audio cuts out after about halfway through the video

### ISSUE THREAD

**Issue by bfosberry** [progweb/gpx2video#20]
**Describe the bug**
For pretty much all of my videos, the audio stream is correct for the first half of the video (not exactly halfway) but after that it goes blank

**To Reproduce**
Steps to reproduce the behavior: (I dont think there are any special steps to reproduce this but Im using 1080x1920 resolution)

**Expected behavior**
Id expect the audio stream to continue to match the video

**Screenshots**

**Desktop (please complete the following information):**
 - OS: osx
 - Version [d298042e5d0bd16eb3eead96b955dc9b769be750]

**Additional context**

**Comment by progweb** [comment]
Should be fixed with last commit [4c093c3ee4a0777b616b4f463ccd4d0ecb28ee18]

**Comment by progweb** [comment]
Done
