### ISSUE TITLE
[BUG] GPX data is offset by exactly the length of the video

### ISSUE THREAD

**Issue by bfosberry** [progweb/gpx2video#21]
**Describe the bug**
When examining the GPX data is seems like the overlay and map data is off by exactly the length of the video. This may be an artifact of how I processed my video and the metadata to this point, but I tried to map the metadata to the final video. 

I'm able to get around this by using ffprobe and setting that as the default offset:
```
  LENGTH="$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $f)"
  OFFSET=$(echo "-1000*$LENGTH" | bc)
```

But if its an internal issue it seems like an easy fix

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by progweb** [comment]
Hi,

Need more info. Can you paste ffprobe output of your input video.

Where does GPX from ? GPS device as Garmin or from GoPro video extraction ? 

At last, can you paste the first lines of your GPX file ?

Of course you can share data files over cloud if you wish.

**Comment by progweb** [comment]
Can't reproduce
