### ISSUE TITLE
[FEATURE] Export overlay sequence to set of PNGs

### ISSUE THREAD

**Issue by cizekmilan** [progweb/gpx2video#22]
**Is your feature request related to a problem? Please describe.**
I would like to have the option for exporting the overlay to PNG files so that I can then use them in another application (Adobe Premiere). For example Garmin VIRB has the same functionality.

**Describe the solution you'd like**
I would like to be able to use an optional parameter to export only the overlay (indicators), e.g. in 1 second intervals.

**Describe alternatives you've considered**
Export only the overlay layer to a video file.

**Comment by progweb** [comment]
Hi,

Feature added in the last commit. Now you can render image per image:

```
$ mkdir png
$ ./gpx2video -v -m GH020340.MP4 -g ACTIVITY.gpx -l layout.xml -o png/image-XXXXXX.png image
```

By default, background is transparent. 

Just use "image" widget to apply background color:

```
      <widget x="0" y="0" width="1920" height="1080" position="none" display="true">
          <type>image</type>
          <background-color>#00aa00ff</background-color>
      </widget>
```
