### ISSUE TITLE
[BUG] increadible text refresh speed

### ISSUE THREAD

**Issue by Re4zOon** [progweb/gpx2video#27]
**Describe the bug**

When doing an OpenStreetMap widget, the text progress line for download gets refreshed as fast as possible.  
I got around 150mbit/s and 50% CPU over SSH just watching the output (from a WSL window, but the actual process runs on my NAS).  
Can you put a sleep there? I guess its eating CPU a lot on the host as well just refreshing the progress bar.

**Comment by progweb** [comment]
Should be fix with last commit c99d498ac7ea7839cad491174e2a769d919962ef
