### ISSUE TITLE
Disable the map and gauges' labels

### ISSUE THREAD

**Issue by lorenz-py** [progweb/gpx2video#3]
Hi, it's me again, 
is it possible to remove the map from the video?
and how can I change the gauges' labels? If I change the layout file the labels remain the same.
Thanks.

**Comment by progweb** [comment]
Hi,

Indeed, it wasn't yet implemented. I have just pushed modifications.

By default, map isn't rendered (except if map-source is defined).
You can change the widget names from the layout file.

At last, you can find new widgets. Of course, if you have more feature requests, you can ask.

**Comment by lorenz-py** [comment]
Now it's perfect, thank you.
