### ISSUE TITLE
[FEATURE] Why is the render part so slow?

### ISSUE THREAD

**Issue by placintaalexandru** [progweb/gpx2video#31]
Let me start with a `thank you for the effort`. The tool looks promising.

**Is your feature request related to a problem? Please describe.**
I am trying to render a 00:05:08 (5 minutes & 8 seconds) 4k GoPro Hero 10 clip with some layouts (I doubt this is the bottleneck) and it takes so long: more than 1 hour to barely render 3 minutes of the video.

**Describe the solution you'd like**
I would like to know what the bottleneck is and, in case you might need help, I would like to help improve this toold using some GPU, if it does not at the moment.
I believe this is a simple and yet good alternative to already existing high fee tools like [telemetry](https://goprotelemetryextractor.com/telemetry-overlay-gps-video-sensors)

**Describe alternatives you've considered**

**Additional context**
OS: `Ubuntu 22.04 LTS`
Arch: `x86_64`
Commit used: `3a9eafcb7478d8b95932b1e494092e2943684b5d`
Command used: `./gpx2video -v -m GH020340.MP4 -g ACTIVITY.gpx -l layout.xml -o output.mp4 video`
GPU: `GeForce GTX 960M`
CPU: `Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz`

**Comment by progweb** [comment]
Hi,

It seems very long for 4k / 5min. 

Of course it depends on number of widgets in your layout and the size of map. 

Please try again with an empty layout. And compare encoding time with ffmpeg tool. You should get an identical time.

Gpx2video supports already gpu encoding. 

```
$ ./gpx2video -v -m GH020340.MP4 -g ACTIVITY.gpx -l layout.xml \
    --video-codec=h264_nvenc --video-preset=ultrafast --video-crf=-1 -o output.mp4 video
```

Options are based on ffmpeg tool.

**Comment by placintaalexandru** [comment]
I am using this as my `layout.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<layout>
	<widget x="250" y="450" width="600" height="120" position="left" align="vertical">
		<type>speed</type>
		<name>Speed</name>
		<margin>20</margin>
		<padding>5</padding>
		<unit>kph</unit>
	</widget>
    <widget x="250" y="450" width="400" height="120" position="left" align="vertical">
		<type>grade</type>
		<name>Inclination</name>
		<margin>20</margin>
		<padding>5</padding>
	</widget>
	<widget x="250" y="450" width="600" height="120" position="left" align="vertical">
		<type>elevation</type>
		<name>Altitude</name>
		<margin>20</margin>
		<padding>5</padding>
		<unit>m</unit>
	</widget>
	<track x="800" y="300" width="640" height="480" position="none" display="false">
	</track>
	<map width="800" height="500" position="bottom-right" display="true">
		<source>1</source>
		<zoom>15</zoom>
		<factor>2.0</factor>
		<margin>20</margin>
		<border>6</border>
		<border-color>#000000ff</border-color>
	</map>
</layout>
```

How does it depend on the number of widgets in the layout file?

I used the ffmpeg tool like this: `ffmpeg -i GX010862.MP4 -c:v libx264 -crf 18 -r 25 -s xga -c:a copy OutputVideo.mkv` (I do not know if it is relevant as baseline and it took ~10 minutes)

**Comment by progweb** [comment]
```
$ ./gpx2video -v -m GH020340.MP4 -g ACTIVITY.gpx -l layout.xml \
    --video-codec=h264 --video-preset=ultrafast --video-crf=18 -o output.mp4 video
```

Can you send me ffprobe output for input video and for output video encoded by ffmpeg.

At first, I see that you drop the framerate from 60 fps to 25 fps. 
Moreover -s xfa resizes video resolution to 1024x768. 

So you should compare with :

```
ffmpeg -i GX010862.MP4 -c:v libx264 -crf 18 -c:a copy OutputVideo.mkv
```

3 widgets don’t affect a lot the rendering process. Map consumes a few cpu mainly if your gpx track is important. 

Gpx2video keeps the same rate & resolution that the input video.

**Comment by placintaalexandru** [comment]
My bad with the framerate. I'll check again with 60 frames

**Comment by placintaalexandru** [comment]
How can I disable the map but still keep the track. I tried with this layout file, but the png renders show invalid and I can't see any widget:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<layout>
	<widget x="250" y="450" width="600" height="120" position="left" align="vertical">
		<type>speed</type>
		<name>Speed</name>
		<margin>20</margin>
		<padding>5</padding>
		<unit>kph</unit>
	</widget>
    <widget x="250" y="450" width="400" height="120" position="left" align="vertical">
		<type>grade</type>
		<name>Inclination</name>
		<margin>20</margin>
		<padding>5</padding>
	</widget>
	<widget x="250" y="450" width="600" height="120" position="left" align="vertical">
		<type>elevation</type>
		<name>Altitude</name>
		<margin>20</margin>
		<padding>5</padding>
		<unit>m</unit>
	</widget>
</layout>

```

**Comment by fpokryvk** [comment]
Hi,
I also noticed performance problems on CPU rendering, also hwaccel Intel QSV is not very satisfactory (I have only intel GPU in my laptop). I noticed that if I try to render images with `./gpx2video ... image` command, the performance is very poor for PNG format, TIFF is way faster (maybe 3x or 4x). I also suppose overlaying over frames in gpx2video might be bottleneck even with hwaccel (at least with QSV), because it utilizes only single CPU core, while encoding the same video with ffmpeg uses rouhgly 4 of 6 cores of the CPU (8 of 12 threads) using QSV hwaccel (and is at least 4x faster), so I currently generate tiff images separately and overlay them using separate ffmpeg command (I do this mainly to deal with timelapse videos, to match GPS data, but it has also performance benefits in my case).

Not sure if relevant, I have no map widget in my layout, only widgets I use are speed, cadence, altitude, gradient and temperature.

**Comment by progweb** [comment]
> How can I disable the map but still keep the track. I tried with this layout file, but the png renders show invalid and I can't see any widget:
> 
> ```
> 	<track x="250" y="450" width="600" height="120" position="bottom-right" display="true">
> </layout>
> ```

To disable widget, you can remove from layout.xml or just use "display" attribute to "false".

**Comment by progweb** [comment]
> Hi, I also noticed performance problems on CPU rendering, also hwaccel Intel QSV is not very satisfactory (I have only intel GPU in my laptop). I noticed that if I try to render images with `./gpx2video ... image` command, the performance is very poor for PNG format, TIFF is way faster (maybe 3x or 4x). I also suppose overlaying over frames in gpx2video might be bottleneck even with hwaccel (at least with QSV), because it utilizes only single CPU core, while encoding the same video with ffmpeg uses rouhgly 4 of 6 cores of the CPU (8 of 12 threads) using QSV hwaccel (and is at least 4x faster), so I currently generate tiff images separately and overlay them using separate ffmpeg command (I do this mainly to deal with timelapse videos, to match GPS data, but it has also performance benefits in my case).
> 
> Not sure if relevant, I have no map widget in my layout, only widgets I use are speed, cadence, altitude, gradient and temperature.

Right for QSV, but in h264 it shouldn't have issues.

**Comment by placintaalexandru** [comment]
> > How can I disable the map but still keep the track. I tried with this layout file, but the png renders show invalid and I can't see any widget:
> > ```
> > 	<track x="250" y="450" width="600" height="120" position="bottom-right" display="true">
> > ```
> 
> To disable widget, you can remove from layout.xml or just use "display" attribute to "false".

I want to enable the widget, but **without** the map

**Comment by placintaalexandru** [comment]
> ```
> $ ./gpx2video -v -m GH020340.MP4 -g ACTIVITY.gpx -l layout.xml \
>     --video-codec=h264 --video-preset=ultrafast --video-crf=18 -o output.mp4 video
> ```
> 
> Can you send me ffprobe output for input video and for output video encoded by ffmpeg.
> 
> At first, I see that you drop the framerate from 60 fps to 25 fps. Moreover -s xfa resizes video resolution to 1024x768.
> 
> So you should compare with :
> 
> ```
> ffmpeg -i GX010862.MP4 -c:v libx264 -crf 18 -c:a copy OutputVideo.mkv
> ```
> 
> 3 widgets don’t affect a lot the rendering process. Map consumes a few cpu mainly if your gpx track is important.
> 
> Gpx2video keeps the same rate & resolution that the input video.

The `ffprobe` on **INPUT**:
```sh
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'GX010866.MP4':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    creation_time   : 2024-03-03T13:31:32.000000Z
    location        : +46.7823+009.6647/
    location-eng    : +46.7823+009.6647/
    firmware        : H21.01.01.50.00
  Duration: 00:04:09.54, start: 0.000000, bitrate: 99744 kb/s
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 99475 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2024-03-03T13:31:32.000000Z
      handler_name    : GoPro H.265
      vendor_id       : [0][0][0][0]
      encoder         : GoPro H.265 encoder
      timecode        : 13:30:43:28
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2024-03-03T13:31:32.000000Z
      handler_name    : GoPro AAC
      vendor_id       : [0][0][0][0]
      timecode        : 13:30:43:28
  Stream #0:2(eng): Data: none (tmcd / 0x64636D74) (default)
    Metadata:
      creation_time   : 2024-03-03T13:31:32.000000Z
      handler_name    : GoPro TCD
      timecode        : 13:30:43:28
  Stream #0:3(eng): Data: bin_data (gpmd / 0x646D7067), 59 kb/s (default)
    Metadata:
      creation_time   : 2024-03-03T13:31:32.000000Z
      handler_name    : GoPro MET
Unsupported codec with id 0 for input stream 2
Unsupported codec with id 100359 for input stream 3
```

`ffprobe` on **ffmpeg's output**:
```sh
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'OutputVideo.mkv':
  Metadata:
    LOCATION-eng    : +46.7823+009.6647/
    MAJOR_BRAND     : mp41
    MINOR_VERSION   : 538120216
    COMPATIBLE_BRANDS: mp41
    FIRMWARE        : H21.01.01.50.00
    LOCATION        : +46.7823+009.6647/
    ENCODER         : Lavf58.76.100
  Duration: 00:04:09.54, start: 0.000000, bitrate: 45115 kb/s
  Stream #0:0(eng): Video: h264 (High), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn, 120 tbc (default)
    Metadata:
      HANDLER_NAME    : GoPro H.265
      VENDOR_ID       : [0][0][0][0]
      TIMECODE        : 13:30:43:28
      ENCODER         : Lavc58.134.100 libx264
      DURATION        : 00:04:09.534000000
  Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      HANDLER_NAME    : GoPro AAC
      VENDOR_ID       : [0][0][0][0]
      TIMECODE        : 13:30:43:28
      DURATION        : 00:04:09.536000000
``

**Comment by placintaalexandru** [comment]
> How can I disable the map but still keep the track. I tried with this layout file, but the png renders show invalid and I can't see any widget:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <layout>
> 	<widget x="250" y="450" width="600" height="120" position="left" align="vertical">
> 		<type>speed</type>
> 		<name>Speed</name>
> 		<margin>20</margin>
> 		<padding>5</padding>
> 		<unit>kph</unit>
> 	</widget>
>     <widget x="250" y="450" width="400" height="120" position="left" align="vertical">
> 		<type>grade</type>
> 		<name>Inclination</name>
> 		<margin>20</margin>
> 		<padding>5</padding>
> 	</widget>
> 	<widget x="250" y="450" width="600" height="120" position="left" align="vertical">
> 		<type>elevation</type>
> 		<name>Altitude</name>
> 		<margin>20</margin>
> 		<padding>5</padding>
> 		<unit>m</unit>
> 	</widget>
> 	<track x="250" y="450" width="600" height="120" position="bottom-right" display="true">
> 		<marker>60</marker>
> 		<border>5</border>
> 		<border-color>#000000b0</border-color>
> 		<background-color>#0000004c</background-color>
> 		<path-thick>3.0</path-thick>
> 		<path-border>1.4</path-border>
> 	</track>
> </layout>
> ```

L.E: nvm, my bad. I was using a wrong `.gpx` file

**Comment by progweb** [comment]
So you are using 4k video in 60fps encoded in hevc... so you need a good cpu :)

Here, I'm often working with 2k video in h264. Here my duration encoding:

Input video: 2 min 38 sec
  Stream #0:0: Video: h264, yuv420p, 2704x1520 [SAR 1:1 DAR 169:95], q=2-31, 50 fps, 50 tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s

h264 (cpu):
~ 24 min

h264_nvenc:
- 18 min

h264_vaapi: 
- 22 min 20 sec

Note: to use nvidia hwaccel, I use optirun since I have 2 gpu boards.
In the 3 cases, video preset is medium and crf is 31.

And for your information, if I'm using hevc:

hevc (cpu):
- 36 min

My laptop doesn't support hevc hardware acceleration :(

**Comment by placintaalexandru** [comment]
Ok, so I removed the map from the layout, ran with your settings and it looks like it's moving faster

The `hevc` part indeed comes from GoPro as it warns you, once you go to `4k 60 FPS`, that your computer must support hevc.
I'll switch for the future and try to film with `2.7k 60 FPS`.

Thank you again for the support on such short notice.

**Comment by progweb** [comment]
I have updated my timing in adding ffmpeg rendering duration.

gpx2video is used with the default layout sample. With an empty layout file, I get about the same timing that ffmpeg.

**Comment by placintaalexandru** [comment]
If there are no other things to discuss, my question is answered so I'll close the issue
