### ISSUE TITLE
[BUG] --start-time not recognized

### ISSUE THREAD

**Issue by mitgolden76** [progweb/gpx2video#32]
**Describe the bug**
When specifying the --start-time option, the following is returned:
`./gpx2video: unrecognized option '--start-time'`
**To Reproduce**
Specify a --start-time value

**Expected behavior**
It runs, setting the creation_time to the specified time.

**Additional context**
It appears that start-time is missing from the options[] in the main file. I added the entry and rebuilt, which yielded the following at runtime:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```
Then I ran again using `--start-time=yyyy-mm-ddT00:00:00Z` format instead of `--start-time "yyyy-mm-ddT00:00:00Z"`
That was successful.

**Comment by progweb** [comment]
Fixed, thank's for report the issue.
