### ISSUE TITLE
[BUILD]

### ISSUE THREAD

**Issue by JesusFork** [progweb/gpx2video#4]
**Describe the build issue**
home/user/gpx2video/src/evcurl.c:5:10: fatal error: openssl/ssl.h: No such file or directory
    5 | #include <openssl/ssl.h>
      |          ^~~~~~~~~~~~~~~

compilation terminated.

**To Reproduce**
Run Make on Ubuntu 21

**Expected behavior**
It should just compile

**Build outputs**
If applicable, add build console outputs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21
 - Virtual Machine

**Comment by progweb** [comment]
Curl package should install SSL packages since, it depends on it.
You have to install "libssl-dev" package.
