### ISSUE TITLE
[BUILD] Ubuntu 24.04 Unable to build on host or using docker

### ISSUE THREAD

**Issue by CarloC-AB** [progweb/gpx2video#41]
### Describe the build issue
I'm unable to build using docker and on host. In docker I get deprecation issues, and building locally, I'm unable to install some of the dependencies since it can't be found

### To Reproduce

**Build in docker**
make build-docker
make build-gpx2video

**build on host**
apt-get install cmake g++ libevent-dev libssl-dev libcurl4-gnutls-dev \
    libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev \
    libswresample-dev libswscale-dev libopenimageio-dev libgeographic-dev \
    libcairo2-dev libopenexr-dev

$ git clone https://github.com/progweb/gpx2video.git
$ mkdir gpx2video/build
$ cd gpx2video/build
$ cmake ..

### Expected behavior
Build succesfully

### Build outputs

**Build in docker**
/app/src/evcurl.c: In function 'evcurl_ssl_ctx_callback':
/app/src/evcurl.c:65:3: warning: 'TLSv1_client_method' is deprecated [-Wdeprecated-declarations]
   65 |   SSL_CTX_set_ssl_version(context, TLSv1_client_method());
      |   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from /app/src/evcurl.c:5:
/usr/include/openssl/ssl.h:1889:1: note: declared here
 1889 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_client_method(void))
      | ^~~~~~~~~~~~~~~~~~
/app/src/evcurl.c:69:3: warning: 'TLSv1_1_client_method' is deprecated [-Wdeprecated-declarations]
   69 |   SSL_CTX_set_ssl_version(context, TLSv1_1_client_method());
      |   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from /app/src/evcurl.c:5:
/usr/include/openssl/ssl.h:1895:1: note: declared here
 1895 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_client_method(void))
      | ^~~~~~~~~~~~~~~~~~
/app/src/evcurl.c:73:3: warning: 'TLSv1_2_client_method' is deprecated [-Wdeprecated-declarations]
   73 |   SSL_CTX_set_ssl_version(context, TLSv1_2_client_method());
      |   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from /app/src/evcurl.c:5:
/usr/include/openssl/ssl.h:1901:1: note: declared here
 1901 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void))
      | ^~~~~~~~~~~~~~~~~~
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/gpxcore.dir/build.make:433: CMakeFiles/gpxcore.dir/src/imagerenderer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:160: CMakeFiles/gpxcore.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
make: *** [Makefile:68: build-gpx2video] Error 2

**build on host**
E: Unable to locate package libavfilter-dev
E: Unable to locate package libopenimageio-dev
E: Unable to locate package libgeographic-dev
E: Unable to locate package libopenexr-dev

CMake Error at /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - libavfilter>=3.0.0

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
  CMakeLists.txt:62 (PKG_CHECK_MODULES)

### Desktop (please complete the following information):
 - OS: Ubuntu
 - Version 24.04

**Comment by progweb** [comment]
Here to build for ubuntu 24.04

First step, prepare docker env with whole necessary packages
Second step, build gpx2video

```
❯ make ubuntu-noble
docker build --build-arg BASE_IMAGE=ubuntu:24.04 \
	-t "gpx2video-ubuntu:24.04" \
	-f docker/Dockerfile .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  5.502GB
Step 1/3 : ARG BASE_IMAGE=debian:11.10-slim
Step 2/3 : FROM ${BASE_IMAGE}
 ---> 59ab366372d5
Step 3/3 : RUN apt-get update     && apt-get --yes --force-yes dist-upgrade     && apt-get install --yes --force-yes --no-install-recommends         procps                 build-essential         cmake         pkg-config                 libevent-dev         libssl-dev         libcurl4-gnutls-dev         libavutil-dev         libavformat-dev         libavcodec-dev         libavfilter-dev         libswresample-dev         libswscale-dev         libopenexr-dev         libopenimageio-dev         libgeographic.*-dev         libcairo2-dev     && rm -rf /var/lib/apt/lists/*     && apt-get clean all
 ---> Running in aa5144775be8
[Get/Unpack/Prepare packages]
Successfully built 869f08d22b71
Successfully tagged gpx2video-ubuntu:24.04
mkdir -p build-ubuntu-noble
docker run --rm -it \
	-u 1000:1000 \
	-v /home/nicolas/Projects/overlay/gpx2video/build-ubuntu-noble:/app/build \
	-v /home/nicolas/Projects/overlay/gpx2video:/app \
	--workdir=/app/build \
	gpx2video-ubuntu:24.04 \
	/bin/bash -c \
	"cmake .. \
	&& make -j"

-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for module 'libevent>=2.0.0'
--   Found libevent, version 2.1.12-stable
-- Checking for module 'libssl>=1.0.0'
--   Found libssl, version 3.0.13
-- Checking for module 'libcurl>=7.38.0'
--   Found libcurl, version 8.5.0
-- Checking for module 'libavutil>=3.0.0'
--   Found libavutil, version 58.29.100
-- Checking for module 'libavformat>=3.0.0'
--   Found libavformat, version 60.16.100
-- Checking for module 'libavcodec>=3.0.0'
--   Found libavcodec, version 60.31.102
-- Checking for module 'libavfilter>=3.0.0'
--   Found libavfilter, version 9.12.100
-- Checking for module 'libswresample>=2.0.0'
--   Found libswresample, version 4.12.100
-- Checking for module 'libswscale>=3.0.0'
--   Found libswscale, version 7.5.100
-- Checking for module 'geographiclib'
--   Found geographiclib, version 2.3
-- Checking for module 'freetype2'
--   Found freetype2, version 26.1.20
-- Checking for module 'cairo'
--   Found cairo, version 1.18.0
-- Found OpenImageIO: /usr/lib/x86_64-linux-gnu/libOpenImageIO.so;/usr/lib/x86_64-linux-gnu/libOpenImageIO_Util.so (found suitable version "2.4.17", minimum required is "2.1.12") 
-- Found EXPAT: /usr/lib/x86_64-linux-gnu/libexpat.so (found version "2.6.1") 
-- Configuring done (1.0s)
-- Generating done (0.0s)
-- Build files have been written to: /app/build
[...]
[ 95%] Linking CXX static library libgpxcore.a
[ 95%] Built target gpxcore
[ 97%] Building CXX object tools/CMakeFiles/gpx2video.dir/gpx2video.cpp.o
[ 97%] Building CXX object tools/CMakeFiles/gpxtools.dir/gpxtools.cpp.o
[ 98%] Linking CXX executable gpxtools
[ 98%] Built target gpxtools
[100%] Linking CXX executable gpx2video
[100%] Built target gpx2video
```

Now, you can update, use gpx2video

```
# To rebuild (after git pull or updated code)
❯ make build-ubuntu-noble
# To run the app (in fact exec bash in docker
❯ make run-ubuntu-noble
ubuntu@21b9a5270374:/app/build$ ./tools/gpx2video --help
# Your host data are in /data
ubuntu@21b9a5270374:/app/build$ ls /data
```
