### ISSUE TITLE
[FEATURE] Trying to build this MacOs

### ISSUE THREAD

**Issue by mstraa** [progweb/gpx2video#5]
Hi ! I'm trying to build it for MacOs (intel). Any tips ?

I will report back here if it's working. 
If not I will use docker and share it :)

**Comment by progweb** [comment]
Hi,

I think that you should be able to build the application on MacOS. 

I don't know how to do it from Linux. If you can provide a mac docker so as I can test and work with it. Or a virtualbox image. 

Regards,

**Comment by bfosberry** [comment]
I used this Dockerfile

```
FROM ubuntu
RUN apt-get update && \
    apt-get install -y cmake g++ libevent-dev libssl-dev libcurl4-gnutls-dev \
    libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev \
    libswresample-dev libswscale-dev libopenimageio-dev libgeographic-dev \
    libcairo2-dev libopenexr-dev
WORKDIR /usr/local/src/gpx2video
ADD . .
RUN rm CMakeCache.txt
RUN cmake .
RUN make
RUN ./gpx2video -h
```

**Comment by progweb** [comment]
Right, but it’s a Linux binary finally. 

I thank that you try to build for Mac in natif.

**Comment by bfosberry** [comment]
I had issues building native in osx, I just used docker wrapping the linux bin to get by, with the container and volumes it acts like a native CLI anyway :P

**Comment by hughsaunders** [comment]
Updated the dockerfile provided by @bfosberry 

```
FROM ubuntu
RUN apt-get update && \
    apt-get install -y cmake g++ libevent-dev libssl-dev libcurl4-gnutls-dev \
    libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev \
    libswresample-dev libswscale-dev libopenimageio-dev libgeographiclib-dev \
    libcairo2-dev libopenexr-dev
WORKDIR /usr/local/src/gpx2video
ADD . .
RUN rm -f CMakeCache.txt
RUN cmake .
RUN make
RUN ./gpx2video -h
```

**Comment by progweb** [comment]
Docker build integrated
