### ISSUE TITLE
[BUG] The time field haven't time zone in GPX file

### ISSUE THREAD

**Issue by Ran-snow** [progweb/gpx2video#9]
Command:
```
./gpx2video -v -m xxxx.MP4 -o output.gpx -f 3 extract
```
Result:
```
...
      <trkpt lat="xxxx" lon="xxxx">
        <ele>38.962</ele>
        <time>2022-06-24T00:21:48.095</time>
      </trkpt>
...
```

I am using this exciting tool to Dashware(overlay gauges tool) , but the display time is wrong.
The reason is that the time in the gpx file does not have a time zone.

I hope so
```
      <trkpt lat="xxxx" lon="xxxx">
        <ele>38.962</ele>
        <time>2022-06-24T00:21:48.095Z</time>
      </trkpt>
```

Add 'Z' in time field 

I'm blank paper in C++ ， so i can't push code ...

Also, are there plans to support Windows?

**Comment by progweb** [comment]
Hi, thank's for the report.

It should fix with the last commit.
